name: Update RSS Feeds Step1

on:
  workflow_dispatch:

jobs:
  fetch-feeds:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Fetch AWS Feed
      run: curl "https://aws.amazon.com/blogs/hpc/feed/" > rss-feeds/public/aws-feed.xml

    - name: Commit and Push
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        git add rss-feeds/public/*.xml
        git commit -m "Updated RSS Feeds" || echo "No changes to commit"
        git push
