name: Update RSS Feeds for GH-Pages

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'  # This runs the action every 6 hours.

jobs:
  fetch-feeds:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout gh-pages branch
      uses: actions/checkout@v2
      with:
        ref: gh-pages
        token: ${{ secrets.MY_GH_TOKEN }}

    - name: Fetch AWS Feed
      run: curl "https://aws.amazon.com/blogs/hpc/feed/" > aws-feed.xml

    - name: Fetch NVIDIA Feed 1
      run: curl "https://feeds.feedburner.com/nvidiablog" > nvidia-feed1.xml

    - name: Fetch NVIDIA Feed 2
      run: curl "https://nvidianews.nvidia.com/releases.xml" > nvidia-feed2.xml

    - name: Commit and Push
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        git add *.xml
        git commit -m "Updated RSS Feeds for GH-Pages" || echo "No changes to commit"
        git push
